#!/usr/bin/env python3
"""
Regenerate src/api/fixtures/phoenix_heatwave_2023.json from the LIVE FortyGuard API.

The original fixture was hand-authored (peak 47.6 C, P40 7.17 h) while being
documented as "cached ground truth" and an "immutable baseline for scientific
reproducibility". The live API reports 42.74 C / 12.0 h for the same place and
date, so replay mode and live mode disagreed and the reproducibility claim was
not true.

This script rebuilds the fixture as a genuine cached API response, so the
offline replay path and the live path return the same physics. Grid-side fields
(wind, load ratio, hospital load, BESS SoC) stay modelled - FortyGuard exposes
no SCADA telemetry - and are copied forward from the existing profile.

    python scripts/regenerate_phoenix_fixture.py

Requires FORTYGUARD_API_KEY. Costs ~18 credits cold, 0 if already cached.
"""
from __future__ import annotations

import asyncio
import json
import sys
from pathlib import Path

from dotenv import load_dotenv

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
load_dotenv(ROOT / ".env")

FIXTURE = ROOT / "src" / "api" / "fixtures" / "phoenix_heatwave_2023.json"

LAT, LON = 33.4484, -112.0740
GRID_FIELDS = (
    "wind_speed_m_s",
    "baseline_load_ratio_k",
    "hospital_critical_load_mw",
    "bess_soc_pct",
)


async def main() -> int:
    from src.api.fortyguard_client import AsyncFortyGuardClient

    client = AsyncFortyGuardClient()
    BENCHMARK_ANALYSIS_DATE = client._resolve_analysis_date(None)
    if client.mock_mode:
        print("ERROR: MOCK_FORTYGUARD_API is on - refusing to write a fixture from mock data.")
        return 1

    existing = json.loads(FIXTURE.read_text())
    old_hours = existing["hourly_forecast_12h"]

    print(f"Fetching live 12h forecast for {BENCHMARK_ANALYSIS_DATE} ...")
    forecast = await client.get_12h_forecast(latitude=LAT, longitude=LON)
    if not forecast or forecast[0].get("data_source", "").startswith("phoenix"):
        print("ERROR: live fetch fell back to the fixture; aborting so we don't bake in mock data.")
        return 1

    print("Fetching live persistence / exceedance ...")
    persistence = await client.get_persistence_and_exceedance(
        LAT, LON, 40.0, hourly_forecast=forecast
    )
    if persistence.get("data_source") != "fortyguard_live":
        print(f"ERROR: persistence came back as {persistence.get('data_source')}; aborting.")
        return 1

    # Carry the modelled grid-side profile forward, indexed by hour so it stays
    # aligned even if the live window shifts.
    grid_by_label = {h.get("time_label"): h for h in old_hours}
    for i, hour in enumerate(forecast):
        src = grid_by_label.get(hour.get("time_label")) or (old_hours[i] if i < len(old_hours) else {})
        for field in GRID_FIELDS:
            if field in src:
                hour[field] = src[field]

    meta = existing["scenario_metadata"]
    meta["name"] = "Phoenix July 2023 Extreme Heatwave Replay (live FortyGuard capture)"
    meta["date_range"] = {
        "start_date": f"{BENCHMARK_ANALYSIS_DATE}T06:00:00Z",
        "end_date": f"{BENCHMARK_ANALYSIS_DATE}T18:00:00Z",
        "filter_type": 2,
    }
    meta["persistence_metrics"] = {
        "threshold_c": persistence["threshold_c"],
        "persistence_hours_p40": persistence["persistence_hours_p40"],
        "exceedance_hours_e40": persistence["exceedance_hours_e40"],
        "exceedance_degree_hours_h40": persistence["exceedance_degree_hours_h40"],
        "thermal_soak_index_tsi": persistence["thermal_soak_index_tsi"],
        "consecutive_heatwave_days": meta["persistence_metrics"]["consecutive_heatwave_days"],
        "n_cells": persistence["n_cells"],
        # Served via the replay route, i.e. a real capture replayed offline.
        "data_source": "phoenix_fixture",
        "analysis_date": persistence["analysis_date"],
    }
    meta["provenance"] = {
        "data_source": "fortyguard_live",
        "analysis_date": persistence["analysis_date"],
        "captured_from": "POST /v1/heatmap (tcm, persistence, exceedance) + POST /v1/env_params",
        "measured_fields": [
            "fortyguard_2m_ambient_c",
            "tile_peak_2m_c",
            "coolest_tile_2m_c",
            "relative_humidity_pct",
            "wet_bulb_temp_c",
            "heat_index_c",
            "cloud_cover_pct",
        ],
        "modelled_fields": list(GRID_FIELDS) + ["solar_irradiance_w_m2"],
        "note": (
            "Regenerated by scripts/regenerate_phoenix_fixture.py. Grid-side fields are "
            "modelled: FortyGuard is an environmental API and exposes no SCADA telemetry."
        ),
    }

    existing["hourly_forecast_12h"] = forecast
    FIXTURE.write_text(json.dumps(existing, indent=2) + "\n")

    peak = max(h["fortyguard_2m_ambient_c"] for h in forecast)
    print(f"\nWrote {FIXTURE.relative_to(ROOT)}")
    print(f"  peak 2m : {peak} C   (was 47.6)")
    print(f"  P40     : {persistence['persistence_hours_p40']} h   (was 7.17)")
    print(f"  H40     : {persistence['exceedance_degree_hours_h40']} C*h   (was 34.25)")
    print(f"  TSI     : {persistence['thermal_soak_index_tsi']}   (was 4.12)")
    return 0


if __name__ == "__main__":
    raise SystemExit(asyncio.run(main()))
